version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android@sha256:5cdc8626cc6f13efe5ed982cdcdb432b0472f8740fed8743a6461e025ad6cdfc
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          command: pwd && ls -a
      - restore_cache:
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./AndroidDemo/gradlew
      - run:
          name: Download Dependencies
          working_directory: ~/code/AndroidDemo
          command: ./gradlew androidDependencies
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - save_cache:
          paths:
            - ~/AndroidDemo/.gradle
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-24;default;armeabi-v7a" && echo "no" | avdmanager create avd -n test -k "system-images;android-24;default;armeabi-v7a"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-arm -avd test -noaudio -no-boot-anim -no-window -accel auto -verbose
          background: true
      - run:
          name: Wait emulator
          command: |
            circle-android wait-for-boot
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest
      - store_artifacts:
          path: AndroidDemo/app/build/reports
          destination: reports
      - store_test_results:
          path: AndroidDemo/app/build/test-results