version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-29-node
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - run:
          command: pwd && ls -a
      - restore_cache:
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./AndroidDemo/gradlew
      - run:
          name: Accept licenses
          command: yes | sdkmanager --licenses || true
      - run:
          name: Download Dependencies
          working_directory: ~/code/AndroidDemo
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/AndroidDemo/.gradle
          key: jars-{{ checksum "AndroidDemo/build.gradle" }}-{{ checksum  "AndroidDemo/app/build.gradle" }}
      - run:
          name: Setup emulator
          command: sdkmanager "system-images;android-27;google_apis;x86" && echo "no" | avdmanager -v create avd -n androidlearn -k "system-images;android-27;google_apis;x86" -c 2048M -g google_apis  -d "Nexus 7 2013"
      - run:
          name: Launch emulator
          command: export LD_LIBRARY_PATH=${ANDROID_HOME}/emulator/lib64:${ANDROID_HOME}/emulator/lib64/qt/lib && emulator64-x86 -avd test -noaudio -no-boot-anim -no-window -accel on
          background: true
      - run:
          name: Wait emulator
          command: |
            # wait for it to have booted
            circle-android wait-for-boot
            # unlock the emulator screen
            sleep 30
            adb shell input keyevent 82
      - run:
          name: Run EspressoTests
          command: ./gradlew connectedDemoDebugAndroidTest
      - store_artifacts:
          path: AndroidDemo/app/build/reports
          destination: reports
      - store_test_results:
          path: AndroidDemo/app/build/test-results